export const popularFoods = [
    "Dosa",
    "Idli",
    "Vada",
    "Sambar",
    "Uttapam",
    "Pongal",
    "Upma",
    "Bisi Bele Bath",
    "Rava Kesari",
    "Rasam",
    "Puliyogare",
    "Masala Dosa",
    "Medu Vada",
    "Pesarattu",
    "Appam",
    "Puttu",
    "Kerala Parotta",
    "Kerala Fish Curry",
    "Avial",
    "Kozhikodan Biryani",
    "Thalassery Biriyani",
    "Malabar Porotta",
    "Kozhikode Halwa",
    "Palada Payasam",
    "Mysore Pak",
    "Kesari Bath",
    "Chitranna",
    "Bonda",
    "Ragi Mudde",
    "Chutney",
    "Sambhar Vada",
    "Kadala Curry",
    "Chana Masala",
    "Aloo Gobi",
    "Paneer Butter Masala",
    "Hyderabadi Biryani",
    "Hyderabadi Haleem",
    "Hyderabadi Dum Pukht",
    "Gongura Chicken",
    "Andhra Chicken Curry",
    "Royyala Iguru",
    "Pulihora",
    "Hyderabadi Mirchi Ka Salan",
    "Andhra Pesarattu",
    "Pootharekulu",
    "Pesarapappu Payasam",
    "Garelu",
    "Boorelu",
    "Kobbari Karam",
    "Karam Podi",
    "Kobbari Pachadi",
    "Vankaya Kothimeera Karam",
    "Gutti Vankaya",
    "Pachi Pulusu",
    "Gongura Pulusu",
    "Ragi Sangati",
    "Kara Pongal",
    "Sakinalu",
    "Ugadi Pachadi",
    "Pootharekulu",
    "Kajjikayalu",
    "Aratikaya Bajji",
    "Pesarapappu Boorelu",
    "Bobbattu",
    "Rava Laddu",
    "Boorelu",
    "Gavvalu",
    "Kudumulu",
    "Garelu",
    "Sajja Rotte",
    "Saggubiyyam Vadiyalu",
    "Pesara Pappu Pachadi",
    "Pappu Chekkalu",
    "Gongura Pachadi",
    "Vankaya Pachadi",
    "Aava Pachadi",
    "Kandi Pachadi",
    "Dosakaya Pachadi",
    "Mango Pachadi",
    "Kobbari Pachadi",
    "Beerakaya Pachadi",
    "Tomato Pachadi",
    "Allam Pachadi",
    "Pudina Pachadi",
    "Cabbage Pachadi",
    "Gongura Pachadi",
    "Vankaya Perugu Pachadi",
    "Dosakaya Perugu Pachadi",
    "Majjiga Pulusu",
    "Tomato Pulusu",
    "Gutti Vankaya Pulusu",
    "Gongura Pulusu",
    "Mango Pulusu",
    "Sorakaya Pulusu",
    "Bendakaya Pulusu",
    "Pappu Pulusu",
    "Chukkakura Pappu",
    "Gongura Pappu",
    "Pachi Pulusu",
    "Chinta Chiguru Pappu",
    "Beerakaya Pappu",
    "Dosakaya Pappu",
    "Vankaya Pappu",
    "Aloo Pappu",
    "Cabbage Pappu",
    "Sorakaya Pappu",
    "Papaya Pappu",
    "Palakoora Pappu",
    "Pappu Charu",
    "Rasam",
    "Pepper Rasam",
    "Lemon Rasam",
    "Pappu Rasam",
    "Gongura Rasam",
    "Tomato Rasam",
    "Mango Rasam",
    // Modern Food Items
    "Pizza",
    "Burger",
    "Pasta",
    "Sandwich",
    "French Fries",
    "Tacos",
    "Sushi",
    "Noodles",
    "Fried Rice",
    "Salad",
    "Grilled Chicken",
    "Steak",
    "Soup",
    "Smoothie",
    "Pancakes",
    "Waffles",
    "Muffins",
    "Cupcakes",
    "Cheesecake",
    "Ice Cream",
    "Brownies",
    "Chocolate Chip Cookies",
    "Donuts",
    "Bagels",
    "Croissants",
    "Quiche",
    "Lasagna",
    "Burrito",
    "Enchiladas",
    "Quesadilla",
    "Nachos",
    "Hamburger",
    "Hot Dog",
    "Fajitas",
    "Kebab",
    "Risotto",
    "Casserole",
    "Frittata",
    "Ratatouille",
    "Gnocchi",
    "Calzone",
    "Tiramisu",
    "Creme Brulee",
    "Macarons",
    "Crepes",
    "Croque Monsieur",
    "Fish and Chips",
    "Shepherd's Pie",
    "Beef Stroganoff",
    "Chicken Tikka Masala",
    "Pad Thai",
    "Pho",
    "Baklava",
    "Biryani",
    "Tandoori Chicken",
    "Pani Puri",
    "Dahi Puri",
    "Samosa",
    "Kathi Roll",
    "Jalebi",
    "Rasgulla",
    "Gulab Jamun"
];
const randomItems = ["Dosa",
    "Idli",
    "Vada",
    "Sambar",
    "Uttapam",
    "Pongal",
    "Upma",
    "Pizza",
    "Burger",
    "Pasta",
    "Sandwich",
    "French Fries",
    "Tacos",]

const randomNames = [
    "Ravi", "Priya", "Suresh", "Meera", "Ajay", "Latha", "Kiran", "Divya", "Arjun", "Shreya", "Aman", "Prakash", "Gowri", "Bhanu"
];

function generateRandomArray() {
    const randomNameIndex = Math.floor(Math.random() * randomNames.length);
    const name = randomNames[randomNameIndex];

    const numItems = Math.floor(Math.random() * 5) + 1; // Randomly choose between 1 and 5 items
    const items = [];
    for (let i = 0; i < numItems; i++) {
        const randomItemIndex = Math.floor(Math.random() * randomItems.length);
        items.push(randomItems[randomItemIndex]);
    }

    return [{ name: name, items: items }];
}

export const arraysToCompare = generateRandomArray();

